// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CapturaOKCode is the HTTP code returned for type CapturaOK
const CapturaOKCode int = 200

/*CapturaOK OK

swagger:response capturaOK
*/
type CapturaOK struct {
}

// NewCapturaOK creates CapturaOK with default headers values
func NewCapturaOK() *CapturaOK {

	return &CapturaOK{}
}

// WriteResponse to the client
func (o *CapturaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
