// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutcapturaOKCode is the HTTP code returned for type PutcapturaOK
const PutcapturaOKCode int = 200

/*PutcapturaOK OK

swagger:response putcapturaOK
*/
type PutcapturaOK struct {
}

// NewPutcapturaOK creates PutcapturaOK with default headers values
func NewPutcapturaOK() *PutcapturaOK {

	return &PutcapturaOK{}
}

// WriteResponse to the client
func (o *PutcapturaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
