// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RefundlistOKCode is the HTTP code returned for type RefundlistOK
const RefundlistOKCode int = 200

/*RefundlistOK OK

swagger:response refundlistOK
*/
type RefundlistOK struct {
}

// NewRefundlistOK creates RefundlistOK with default headers values
func NewRefundlistOK() *RefundlistOK {

	return &RefundlistOK{}
}

// WriteResponse to the client
func (o *RefundlistOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
