// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRefundlistParams creates a new RefundlistParams object
// no default values defined in spec.
func NewRefundlistParams() RefundlistParams {

	return RefundlistParams{}
}

// RefundlistParams contains all the bound params for the refundlist operation
// typically these are obtained from a http.Request
//
// swagger:parameters refundlist
type RefundlistParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	RefundID string
	/*
	  Required: true
	  In: path
	*/
	Tid string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRefundlistParams() beforehand.
func (o *RefundlistParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRefundID, rhkRefundID, _ := route.Params.GetOK("refundId")
	if err := o.bindRefundID(rRefundID, rhkRefundID, route.Formats); err != nil {
		res = append(res, err)
	}

	rTid, rhkTid, _ := route.Params.GetOK("tid")
	if err := o.bindTid(rTid, rhkTid, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRefundID binds and validates parameter RefundID from path.
func (o *RefundlistParams) bindRefundID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.RefundID = raw

	return nil
}

// bindTid binds and validates parameter Tid from path.
func (o *RefundlistParams) bindTid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Tid = raw

	return nil
}
