// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRefundsTidParams creates a new RefundsTidParams object
// no default values defined in spec.
func NewRefundsTidParams() RefundsTidParams {

	return RefundsTidParams{}
}

// RefundsTidParams contains all the bound params for the refunds tid operation
// typically these are obtained from a http.Request
//
// swagger:parameters refunds_tid
type RefundsTidParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Tid string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRefundsTidParams() beforehand.
func (o *RefundsTidParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTid, rhkTid, _ := route.Params.GetOK("tid")
	if err := o.bindTid(rTid, rhkTid, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTid binds and validates parameter Tid from path.
func (o *RefundsTidParams) bindTid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Tid = raw

	return nil
}
