// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RefundsTidHandlerFunc turns a function with the right signature into a refunds tid handler
type RefundsTidHandlerFunc func(RefundsTidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RefundsTidHandlerFunc) Handle(params RefundsTidParams) middleware.Responder {
	return fn(params)
}

// RefundsTidHandler interface for that can handle valid refunds tid params
type RefundsTidHandler interface {
	Handle(RefundsTidParams) middleware.Responder
}

// NewRefundsTid creates a new http.Handler for the refunds tid operation
func NewRefundsTid(ctx *middleware.Context, handler RefundsTidHandler) *RefundsTid {
	return &RefundsTid{Context: ctx, Handler: handler}
}

/*RefundsTid swagger:route GET /desenvolvedores/v1/transactions/{tid}/refunds refundsTid

refunds_tid

Consulta de cancelamento por tid.

*/
type RefundsTid struct {
	Context *middleware.Context
	Handler RefundsTidHandler
}

func (o *RefundsTid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRefundsTidParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
