// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RefundsTidOKCode is the HTTP code returned for type RefundsTidOK
const RefundsTidOKCode int = 200

/*RefundsTidOK OK

swagger:response refundsTidOK
*/
type RefundsTidOK struct {
}

// NewRefundsTidOK creates RefundsTidOK with default headers values
func NewRefundsTidOK() *RefundsTidOK {

	return &RefundsTidOK{}
}

// WriteResponse to the client
func (o *RefundsTidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
