// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TransaçãoNoContentCode is the HTTP code returned for type TransaçãoNoContent
const TransaçãoNoContentCode int = 204

/*TransaçãoNoContent No Content

swagger:response transaçãoNoContent
*/
type TransaçãoNoContent struct {
}

// NewTransaçãoNoContent creates TransaçãoNoContent with default headers values
func NewTransaçãoNoContent() *TransaçãoNoContent {

	return &TransaçãoNoContent{}
}

// WriteResponse to the client
func (o *TransaçãoNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
