// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TransaçãoReferenceHandlerFunc turns a function with the right signature into a transação reference handler
type TransaçãoReferenceHandlerFunc func(TransaçãoReferenceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TransaçãoReferenceHandlerFunc) Handle(params TransaçãoReferenceParams) middleware.Responder {
	return fn(params)
}

// TransaçãoReferenceHandler interface for that can handle valid transação reference params
type TransaçãoReferenceHandler interface {
	Handle(TransaçãoReferenceParams) middleware.Responder
}

// NewTransaçãoReference creates a new http.Handler for the transação reference operation
func NewTransaçãoReference(ctx *middleware.Context, handler TransaçãoReferenceHandler) *TransaçãoReference {
	return &TransaçãoReference{Context: ctx, Handler: handler}
}

/*TransaçãoReference swagger:route GET /desenvolvedores/v1/transactions/ transaçãoReference

transação_reference

Consulta da transação por reference.

*/
type TransaçãoReference struct {
	Context *middleware.Context
	Handler TransaçãoReferenceHandler
}

func (o *TransaçãoReference) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTransaçãoReferenceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
