// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Swagger API

    Schemes:
      http
    Host: api.userede.com.br
    BasePath: /
    Version: 1.0
    Contact:

    Consumes:
    - application/json
    - application/x-www-form-urlencoded

    Produces:
    - application/json

swagger:meta
*/
package restapi
