// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swagger API",
    "contact": {},
    "version": "1.0"
  },
  "host": "api.userede.com.br",
  "basePath": "/",
  "paths": {
    "/desenvolvedores/v1/transactions/": {
      "get": {
        "security": [],
        "description": "Consulta da transação por reference.",
        "produces": [
          "application/json"
        ],
        "summary": "transação_reference",
        "operationId": "transação_reference",
        "parameters": [
          {
            "type": "string",
            "name": "reference",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "security": [],
        "description": "A autorização é o primeiro passo para realizar uma transação.",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "transação",
        "operationId": "transação",
        "parameters": [
          {
            "type": "string",
            "name": "Transaction",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "Transaction3DSRede",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "Transaction3DSClient",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/desenvolvedores/v1/transactions/{tid}": {
      "get": {
        "security": [],
        "description": "Consulta da transação por TID.",
        "produces": [
          "application/json"
        ],
        "summary": "captura",
        "operationId": "captura",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "put": {
        "security": [],
        "description": "Confirma a autorização da transação (captura).",
        "produces": [
          "application/json"
        ],
        "summary": "captura",
        "operationId": "Putcaptura",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/desenvolvedores/v1/transactions/{tid}/refunds": {
      "get": {
        "security": [],
        "description": "Consulta de cancelamento por tid.",
        "produces": [
          "application/json"
        ],
        "summary": "refunds_tid",
        "operationId": "refunds_tid",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "security": [],
        "description": "Realiza o cancelamento da transação.",
        "produces": [
          "application/json"
        ],
        "summary": "refund",
        "operationId": "refund",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/desenvolvedores/v1/transactions/{tid}/refunds/{refundId}": {
      "get": {
        "security": [],
        "description": "Consulta de cancelamento por refundId.",
        "produces": [
          "application/json"
        ],
        "summary": "refund list",
        "operationId": "refundlist",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "refundId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "RefundRequest": {
      "type": "object",
      "title": "RefundRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        }
      }
    },
    "Transaction3DSClientRequest": {
      "type": "object",
      "title": "Transaction3DSClientRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        },
        "cardNumber": {
          "type": "string",
          "default": "5448280000000007",
          "example": 5448280000000007
        },
        "cardholderName": {
          "type": "string",
          "default": "Pedro da Silva",
          "example": "Pedro da Silva"
        },
        "expirationMonth": {
          "type": "number",
          "format": "double",
          "default": 12,
          "example": 12
        },
        "expirationYear": {
          "type": "number",
          "format": "double",
          "default": 2020,
          "example": 2020
        },
        "reference": {
          "type": "string",
          "default": "pedido12321",
          "example": "pedido12321"
        },
        "securityCode": {
          "type": "string",
          "default": "123",
          "example": 123
        },
        "threeDSecure": {
          "$ref": "#/definitions/threeDSecureClient"
        }
      }
    },
    "Transaction3DSRedeRequest": {
      "type": "object",
      "title": "Transaction3DSRedeRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        },
        "capture": {
          "type": "boolean",
          "default": false,
          "example": false
        },
        "cardNumber": {
          "type": "string",
          "default": "2223000148400010",
          "example": 2223000148400010
        },
        "cardholderName": {
          "type": "string",
          "default": "Pedro da Silva",
          "example": "Pedro da Silva"
        },
        "expirationMonth": {
          "type": "number",
          "format": "double",
          "default": 12,
          "example": 12
        },
        "expirationYear": {
          "type": "number",
          "format": "double",
          "default": 2020,
          "example": 2020
        },
        "kind": {
          "type": "string",
          "default": "debit",
          "example": "debit"
        },
        "reference": {
          "type": "string",
          "default": "pedido2",
          "example": "pedido2"
        },
        "securityCode": {
          "type": "string",
          "default": "123",
          "example": 123
        },
        "threeDSecure": {
          "$ref": "#/definitions/threeDSecureRede"
        },
        "urls": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/urlsThreeDSecureRede"
          }
        }
      }
    },
    "TransactionRequest": {
      "type": "object",
      "title": "TransactionRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        },
        "capture": {
          "type": "boolean",
          "default": false,
          "example": false
        },
        "cardNumber": {
          "type": "string",
          "default": "5448280000000007",
          "example": 5448280000000007
        },
        "cardholderName": {
          "type": "string",
          "default": "Pedro da Silva",
          "example": "Pedro da Silva"
        },
        "expirationMonth": {
          "type": "number",
          "format": "double",
          "default": 12,
          "example": 12
        },
        "expirationYear": {
          "type": "number",
          "format": "double",
          "default": 2020,
          "example": 2020
        },
        "reference": {
          "type": "string",
          "default": "pedido1",
          "example": "pedido1"
        },
        "securityCode": {
          "type": "string",
          "default": "123",
          "example": 123
        }
      }
    },
    "threeDSecureClient": {
      "type": "object",
      "title": "threeDSecureClient",
      "properties": {
        "cavv": {
          "type": "string",
          "default": "BwABBylVaQAAAAFwllVpAAAAAAA=",
          "example": "BwABBylVaQAAAAFwllVpAAAAAAA="
        },
        "eci": {
          "type": "string",
          "default": "05",
          "example": 5
        },
        "embedded": {
          "type": "boolean",
          "default": false,
          "example": false
        },
        "xid": {
          "type": "string",
          "default": "Nmp3VFdWMlEwZ05pWGN3SGo4TDA=",
          "example": "Nmp3VFdWMlEwZ05pWGN3SGo4TDA="
        }
      }
    },
    "threeDSecureRede": {
      "type": "object",
      "title": "threeDSecureRede",
      "properties": {
        "embedded": {
          "type": "boolean",
          "default": true,
          "example": true
        },
        "onFailure": {
          "type": "string",
          "default": "decline",
          "example": "decline"
        },
        "userAgent": {
          "type": "string",
          "default": "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405",
          "example": "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405"
        }
      }
    },
    "urlsThreeDSecureRede": {
      "type": "object",
      "title": "urlsThreeDSecureRede",
      "properties": {
        "kind": {
          "type": "string",
          "default": "threeDSecureSuccess",
          "example": "threeDSecureSuccess"
        },
        "url": {
          "type": "string",
          "default": "https://redirecturl.com/3ds/success",
          "example": "https://redirecturl.com/3ds/success"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swagger API",
    "contact": {},
    "version": "1.0"
  },
  "host": "api.userede.com.br",
  "basePath": "/",
  "paths": {
    "/desenvolvedores/v1/transactions/": {
      "get": {
        "security": [],
        "description": "Consulta da transação por reference.",
        "produces": [
          "application/json"
        ],
        "summary": "transação_reference",
        "operationId": "transação_reference",
        "parameters": [
          {
            "type": "string",
            "name": "reference",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "security": [],
        "description": "A autorização é o primeiro passo para realizar uma transação.",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "transação",
        "operationId": "transação",
        "parameters": [
          {
            "type": "string",
            "name": "Transaction",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "Transaction3DSRede",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "Transaction3DSClient",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/desenvolvedores/v1/transactions/{tid}": {
      "get": {
        "security": [],
        "description": "Consulta da transação por TID.",
        "produces": [
          "application/json"
        ],
        "summary": "captura",
        "operationId": "captura",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "put": {
        "security": [],
        "description": "Confirma a autorização da transação (captura).",
        "produces": [
          "application/json"
        ],
        "summary": "captura",
        "operationId": "Putcaptura",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/desenvolvedores/v1/transactions/{tid}/refunds": {
      "get": {
        "security": [],
        "description": "Consulta de cancelamento por tid.",
        "produces": [
          "application/json"
        ],
        "summary": "refunds_tid",
        "operationId": "refunds_tid",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "security": [],
        "description": "Realiza o cancelamento da transação.",
        "produces": [
          "application/json"
        ],
        "summary": "refund",
        "operationId": "refund",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/desenvolvedores/v1/transactions/{tid}/refunds/{refundId}": {
      "get": {
        "security": [],
        "description": "Consulta de cancelamento por refundId.",
        "produces": [
          "application/json"
        ],
        "summary": "refund list",
        "operationId": "refundlist",
        "parameters": [
          {
            "type": "string",
            "name": "tid",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "refundId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "RefundRequest": {
      "type": "object",
      "title": "RefundRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        }
      }
    },
    "Transaction3DSClientRequest": {
      "type": "object",
      "title": "Transaction3DSClientRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        },
        "cardNumber": {
          "type": "string",
          "default": "5448280000000007",
          "example": 5448280000000007
        },
        "cardholderName": {
          "type": "string",
          "default": "Pedro da Silva",
          "example": "Pedro da Silva"
        },
        "expirationMonth": {
          "type": "number",
          "format": "double",
          "default": 12,
          "example": 12
        },
        "expirationYear": {
          "type": "number",
          "format": "double",
          "default": 2020,
          "example": 2020
        },
        "reference": {
          "type": "string",
          "default": "pedido12321",
          "example": "pedido12321"
        },
        "securityCode": {
          "type": "string",
          "default": "123",
          "example": 123
        },
        "threeDSecure": {
          "$ref": "#/definitions/threeDSecureClient"
        }
      }
    },
    "Transaction3DSRedeRequest": {
      "type": "object",
      "title": "Transaction3DSRedeRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        },
        "capture": {
          "type": "boolean",
          "default": false,
          "example": false
        },
        "cardNumber": {
          "type": "string",
          "default": "2223000148400010",
          "example": 2223000148400010
        },
        "cardholderName": {
          "type": "string",
          "default": "Pedro da Silva",
          "example": "Pedro da Silva"
        },
        "expirationMonth": {
          "type": "number",
          "format": "double",
          "default": 12,
          "example": 12
        },
        "expirationYear": {
          "type": "number",
          "format": "double",
          "default": 2020,
          "example": 2020
        },
        "kind": {
          "type": "string",
          "default": "debit",
          "example": "debit"
        },
        "reference": {
          "type": "string",
          "default": "pedido2",
          "example": "pedido2"
        },
        "securityCode": {
          "type": "string",
          "default": "123",
          "example": 123
        },
        "threeDSecure": {
          "$ref": "#/definitions/threeDSecureRede"
        },
        "urls": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/urlsThreeDSecureRede"
          }
        }
      }
    },
    "TransactionRequest": {
      "type": "object",
      "title": "TransactionRequest",
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "default": 1000,
          "example": 1000
        },
        "capture": {
          "type": "boolean",
          "default": false,
          "example": false
        },
        "cardNumber": {
          "type": "string",
          "default": "5448280000000007",
          "example": 5448280000000007
        },
        "cardholderName": {
          "type": "string",
          "default": "Pedro da Silva",
          "example": "Pedro da Silva"
        },
        "expirationMonth": {
          "type": "number",
          "format": "double",
          "default": 12,
          "example": 12
        },
        "expirationYear": {
          "type": "number",
          "format": "double",
          "default": 2020,
          "example": 2020
        },
        "reference": {
          "type": "string",
          "default": "pedido1",
          "example": "pedido1"
        },
        "securityCode": {
          "type": "string",
          "default": "123",
          "example": 123
        }
      }
    },
    "threeDSecureClient": {
      "type": "object",
      "title": "threeDSecureClient",
      "properties": {
        "cavv": {
          "type": "string",
          "default": "BwABBylVaQAAAAFwllVpAAAAAAA=",
          "example": "BwABBylVaQAAAAFwllVpAAAAAAA="
        },
        "eci": {
          "type": "string",
          "default": "05",
          "example": 5
        },
        "embedded": {
          "type": "boolean",
          "default": false,
          "example": false
        },
        "xid": {
          "type": "string",
          "default": "Nmp3VFdWMlEwZ05pWGN3SGo4TDA=",
          "example": "Nmp3VFdWMlEwZ05pWGN3SGo4TDA="
        }
      }
    },
    "threeDSecureRede": {
      "type": "object",
      "title": "threeDSecureRede",
      "properties": {
        "embedded": {
          "type": "boolean",
          "default": true,
          "example": true
        },
        "onFailure": {
          "type": "string",
          "default": "decline",
          "example": "decline"
        },
        "userAgent": {
          "type": "string",
          "default": "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405",
          "example": "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405"
        }
      }
    },
    "urlsThreeDSecureRede": {
      "type": "object",
      "title": "urlsThreeDSecureRede",
      "properties": {
        "kind": {
          "type": "string",
          "default": "threeDSecureSuccess",
          "example": "threeDSecureSuccess"
        },
        "url": {
          "type": "string",
          "default": "https://redirecturl.com/3ds/success",
          "example": "https://redirecturl.com/3ds/success"
        }
      }
    }
  }
}`))
}
