// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ThreeDSecureClient threeDSecureClient
// swagger:model threeDSecureClient
type ThreeDSecureClient struct {

	// cavv
	Cavv *string `json:"cavv,omitempty"`

	// eci
	Eci *string `json:"eci,omitempty"`

	// embedded
	Embedded *bool `json:"embedded,omitempty"`

	// xid
	Xid *string `json:"xid,omitempty"`
}

// Validate validates this three d secure client
func (m *ThreeDSecureClient) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThreeDSecureClient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThreeDSecureClient) UnmarshalBinary(b []byte) error {
	var res ThreeDSecureClient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
