// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ThreeDSecureRede threeDSecureRede
// swagger:model threeDSecureRede
type ThreeDSecureRede struct {

	// embedded
	Embedded *bool `json:"embedded,omitempty"`

	// on failure
	OnFailure *string `json:"onFailure,omitempty"`

	// user agent
	UserAgent *string `json:"userAgent,omitempty"`
}

// Validate validates this three d secure rede
func (m *ThreeDSecureRede) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThreeDSecureRede) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThreeDSecureRede) UnmarshalBinary(b []byte) error {
	var res ThreeDSecureRede
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
