// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Transaction3DSRedeRequest Transaction3DSRedeRequest
// swagger:model Transaction3DSRedeRequest
type Transaction3DSRedeRequest struct {

	// amount
	Amount *float64 `json:"amount,omitempty"`

	// capture
	Capture *bool `json:"capture,omitempty"`

	// card number
	CardNumber *string `json:"cardNumber,omitempty"`

	// cardholder name
	CardholderName *string `json:"cardholderName,omitempty"`

	// expiration month
	ExpirationMonth *float64 `json:"expirationMonth,omitempty"`

	// expiration year
	ExpirationYear *float64 `json:"expirationYear,omitempty"`

	// kind
	Kind *string `json:"kind,omitempty"`

	// reference
	Reference *string `json:"reference,omitempty"`

	// security code
	SecurityCode *string `json:"securityCode,omitempty"`

	// three d secure
	ThreeDSecure *ThreeDSecureRede `json:"threeDSecure,omitempty"`

	// urls
	Urls []*UrlsThreeDSecureRede `json:"urls"`
}

// Validate validates this transaction3 d s rede request
func (m *Transaction3DSRedeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateThreeDSecure(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUrls(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Transaction3DSRedeRequest) validateThreeDSecure(formats strfmt.Registry) error {

	if swag.IsZero(m.ThreeDSecure) { // not required
		return nil
	}

	if m.ThreeDSecure != nil {
		if err := m.ThreeDSecure.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("threeDSecure")
			}
			return err
		}
	}

	return nil
}

func (m *Transaction3DSRedeRequest) validateUrls(formats strfmt.Registry) error {

	if swag.IsZero(m.Urls) { // not required
		return nil
	}

	for i := 0; i < len(m.Urls); i++ {
		if swag.IsZero(m.Urls[i]) { // not required
			continue
		}

		if m.Urls[i] != nil {
			if err := m.Urls[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("urls" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Transaction3DSRedeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Transaction3DSRedeRequest) UnmarshalBinary(b []byte) error {
	var res Transaction3DSRedeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
