// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TransactionRequest TransactionRequest
// swagger:model TransactionRequest
type TransactionRequest struct {

	// amount
	Amount *float64 `json:"amount,omitempty"`

	// capture
	Capture *bool `json:"capture,omitempty"`

	// card number
	CardNumber *string `json:"cardNumber,omitempty"`

	// cardholder name
	CardholderName *string `json:"cardholderName,omitempty"`

	// expiration month
	ExpirationMonth *float64 `json:"expirationMonth,omitempty"`

	// expiration year
	ExpirationYear *float64 `json:"expirationYear,omitempty"`

	// reference
	Reference *string `json:"reference,omitempty"`

	// security code
	SecurityCode *string `json:"securityCode,omitempty"`
}

// Validate validates this transaction request
func (m *TransactionRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionRequest) UnmarshalBinary(b []byte) error {
	var res TransactionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
